# Generated by Django 5.1.4 on 2025-01-10 12:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True)),
                ("updated_in_mneia", models.DateTimeField(auto_now=True)),
                ("mbid", models.IntegerField(help_text="The MusicBrainz integer ID", verbose_name="MBID")),
                ("name", models.CharField(max_length=255)),
                ("child_order", models.IntegerField(verbose_name="Child Order")),
                ("description", models.TextField(null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.areatype"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Area Types",
                "ordering": ["name"],
            },
        ),
    ]
