# Generated by Django 5.1.4 on 2025-01-11 10:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True)),
                ("updated_in_mneia", models.DateTimeField(auto_now=True)),
                ("mbid", models.IntegerField(verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("edits_pending", models.PositiveIntegerField(default=0, verbose_name="Edits Pending")),
                ("last_updated", models.DateTimeField(verbose_name="Last Updated")),
                ("begin_date_year", models.SmallIntegerField(null=True, verbose_name="Begin Date Year")),
                ("begin_date_month", models.SmallIntegerField(null=True, verbose_name="Begin Date Month")),
                ("begin_date_day", models.SmallIntegerField(null=True, verbose_name="Begin Date Day")),
                ("end_date_year", models.SmallIntegerField(null=True, verbose_name="End Date Year")),
                ("end_date_month", models.SmallIntegerField(null=True, verbose_name="End Date Month")),
                ("end_date_day", models.SmallIntegerField(null=True, verbose_name="End Date Day")),
                ("ended", models.BooleanField(default=False, verbose_name="Ended?")),
                ("comment", models.CharField(default="", max_length=255)),
                (
                    "type",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.areatype"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Areas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True)),
                ("updated_in_mneia", models.DateTimeField(auto_now=True)),
                ("mbid", models.IntegerField(help_text="The MusicBrainz integer ID", verbose_name="MBID")),
                ("name", models.CharField(max_length=255)),
                ("child_order", models.IntegerField(verbose_name="Child Order")),
                ("description", models.TextField(null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.gender"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Genders",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True)),
                ("updated_in_mneia", models.DateTimeField(auto_now=True)),
                ("mbid", models.IntegerField(verbose_name="MBID")),
                ("name", models.CharField(max_length=255)),
                ("sort_name", models.CharField(max_length=255, verbose_name="Sort Name")),
                ("begin_date_year", models.SmallIntegerField(null=True, verbose_name="Begin Date Year")),
                ("begin_date_month", models.SmallIntegerField(null=True, verbose_name="Begin Date Month")),
                ("begin_date_day", models.SmallIntegerField(null=True, verbose_name="Begin Date Day")),
                ("end_date_year", models.SmallIntegerField(null=True, verbose_name="End Date Year")),
                ("end_date_month", models.SmallIntegerField(null=True, verbose_name="End Date Month")),
                ("end_date_day", models.SmallIntegerField(null=True, verbose_name="End Date Day")),
                ("comment", models.CharField(default="", max_length=255)),
                ("edits_pending", models.PositiveIntegerField(default=0, verbose_name="Edits Pending")),
                ("last_updated", models.DateTimeField(verbose_name="Last Updated")),
                ("ended", models.BooleanField(default=False, verbose_name="Ended?")),
                (
                    "area",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.area"),
                ),
                (
                    "begin_area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="people_begin_area",
                        to="mneia_backend.area",
                        verbose_name="Begin Area",
                    ),
                ),
                (
                    "end_area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="people_end_area",
                        to="mneia_backend.area",
                        verbose_name="End Area",
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.gender"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "People",
                "ordering": ["name"],
            },
        ),
    ]
