# Generated by Django 5.1.4 on 2025-01-14 08:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0004_linktype_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkPersonPhotograph",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True)),
                ("updated_in_mneia", models.DateTimeField(auto_now=True)),
                ("mbid", models.IntegerField(help_text="The MusicBrainz integer ID", null=True, verbose_name="MBID")),
                ("edits_pending", models.PositiveIntegerField(default=0, verbose_name="Edits Pending")),
                ("last_updated", models.DateTimeField(auto_now=True, verbose_name="Last Updated")),
                ("link_order", models.PositiveIntegerField(default=0, null=True, verbose_name="Link Order")),
                ("entity0_credit", models.TextField(default="")),
                ("entity1_credit", models.TextField(default="")),
                ("link", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.link")),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.person")),
                (
                    "photograph",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.photograph"),
                ),
            ],
            options={
                "verbose_name_plural": "Links Person-Photograph",
            },
        ),
    ]
