# Generated by Django 5.1.4 on 2025-01-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0005_linkpersonphotograph"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linktype",
            name="entity_type0",
            field=models.CharField(choices=[("person", "person")], max_length=50, verbose_name="Entity Type 0"),
        ),
        migrations.AlterField(
            model_name="linktype",
            name="entity_type1",
            field=models.CharField(choices=[("photograph", "photograph")], max_length=50, verbose_name="Entity Type 1"),
        ),
        migrations.AlterField(
            model_name="linktype",
            name="mbid",
            field=models.IntegerField(null=True, verbose_name="MBID"),
        ),
    ]
