# Generated by Django 5.1.4 on 2025-01-14 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0007_alter_link_begin_date_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="mbid",
            field=models.IntegerField(verbose_name="MBID"),
        ),
        migrations.AlterField(
            model_name="person",
            name="begin_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="people_begin_area",
                to="mneia_backend.area",
                verbose_name="Begin Area",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="begin_date_day",
            field=models.SmallIntegerField(blank=True, null=True, verbose_name="Begin Date Day"),
        ),
        migrations.AlterField(
            model_name="person",
            name="begin_date_month",
            field=models.SmallIntegerField(blank=True, null=True, verbose_name="Begin Date Month"),
        ),
        migrations.AlterField(
            model_name="person",
            name="begin_date_year",
            field=models.SmallIntegerField(blank=True, null=True, verbose_name="Begin Date Year"),
        ),
        migrations.AlterField(
            model_name="person",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="person",
            name="end_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="people_end_area",
                to="mneia_backend.area",
                verbose_name="End Area",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="end_date_day",
            field=models.SmallIntegerField(blank=True, null=True, verbose_name="End Date Day"),
        ),
        migrations.AlterField(
            model_name="person",
            name="end_date_month",
            field=models.SmallIntegerField(blank=True, null=True, verbose_name="End Date Month"),
        ),
        migrations.AlterField(
            model_name="person",
            name="end_date_year",
            field=models.SmallIntegerField(blank=True, null=True, verbose_name="End Date Year"),
        ),
    ]
