# Generated by Django 5.1.4 on 2025-01-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0009_alter_person_mbid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
        ),
    ]
