# Generated by Django 5.1.4 on 2025-01-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0010_alter_person_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkpersonphotograph",
            name="entity0_credit",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="linkpersonphotograph",
            name="entity1_credit",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="linkpersonphotograph",
            name="mbid",
            field=models.IntegerField(
                blank=True, help_text="The MusicBrainz integer ID", null=True, verbose_name="MBID"
            ),
        ),
    ]
