# Generated by Django 5.1.5 on 2025-01-22 12:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0012_remove_linktype_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkAttributeType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True)),
                ("updated_in_mneia", models.DateTimeField(auto_now=True)),
                ("mbid", models.IntegerField(null=True, verbose_name="MBID")),
                (
                    "child_order",
                    models.IntegerField(default=0, verbose_name="Child Order"),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(db_column="description", null=True)),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_link_attribute_types",
                        to="mneia_backend.linkattributetype",
                    ),
                ),
                (
                    "root",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leaf_child_attribute_types",
                        to="mneia_backend.linkattributetype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Link Attribute Types",
            },
        ),
    ]
