# Generated by Django 5.1.5 on 2025-01-24 12:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0013_linkattributetype"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkAttribute",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True)),
                ("updated_in_mneia", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "attribute_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.linkattributetype"
                    ),
                ),
                ("link", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.link")),
            ],
            options={
                "verbose_name_plural": "Link Attributes",
                "constraints": [models.UniqueConstraint(fields=("link", "attribute_type"), name="unique_together")],
            },
        ),
    ]
