# Generated by Django 5.1.5 on 2025-01-26 06:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0014_linkattribute"),
    ]

    operations = [
        migrations.CreateModel(
            name="Magazine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True)),
                ("updated_in_mneia", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LinkTextAttributeType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True)),
                ("updated_in_mneia", models.DateTimeField(auto_now=True)),
                (
                    "attribute_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.linkattributetype"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Link Text Attribute Types",
            },
        ),
        migrations.CreateModel(
            name="LinkAttributeTextValue",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True)),
                ("updated_in_mneia", models.DateTimeField(auto_now=True)),
                ("text_value", models.TextField()),
                ("link", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.link")),
                (
                    "attribute_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.linktextattributetype"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Link Attribute Text Values",
            },
        ),
        migrations.CreateModel(
            name="MagazineIssue",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True)),
                ("updated_in_mneia", models.DateTimeField(auto_now=True)),
                ("issue_number", models.CharField(max_length=15)),
                ("order", models.PositiveSmallIntegerField()),
                ("date_published", models.DateField()),
                (
                    "magazine",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.magazine"),
                ),
            ],
            options={
                "verbose_name_plural": "Magazine Issues",
            },
        ),
        migrations.CreateModel(
            name="LinkMagazineIssuePhotograph",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True)),
                ("updated_in_mneia", models.DateTimeField(auto_now=True)),
                (
                    "mbid",
                    models.IntegerField(
                        blank=True, help_text="The MusicBrainz integer ID", null=True, verbose_name="MBID"
                    ),
                ),
                ("edits_pending", models.PositiveIntegerField(default=0, verbose_name="Edits Pending")),
                ("last_updated", models.DateTimeField(auto_now=True, verbose_name="Last Updated")),
                ("link_order", models.PositiveIntegerField(default=0, null=True, verbose_name="Link Order")),
                ("entity0_credit", models.TextField(blank=True, default="")),
                ("entity1_credit", models.TextField(blank=True, default="")),
                ("link", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.link")),
                (
                    "photograph",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.photograph"),
                ),
                (
                    "magazine_issue",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.magazineissue"),
                ),
            ],
            options={
                "verbose_name_plural": "Links MagazineIssue-Photograph",
            },
        ),
        migrations.AddConstraint(
            model_name="linktextattributetype",
            constraint=models.UniqueConstraint(fields=("attribute_type",), name="unique"),
        ),
        migrations.AddConstraint(
            model_name="linkattributetextvalue",
            constraint=models.UniqueConstraint(
                fields=("link", "attribute_type"), name="link_and_attribute_type_are_unique_together"
            ),
        ),
    ]
