# Generated by Django 5.1.5 on 2025-01-26 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0015_magazine_linktextattributetype_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="linkmagazineissuephotograph",
            options={"verbose_name_plural": "Links Magazine Issue - Photograph"},
        ),
        migrations.AlterModelOptions(
            name="linkpersonphotograph",
            options={"verbose_name_plural": "Links Person - Photograph"},
        ),
        migrations.AlterField(
            model_name="area",
            name="created_in_mneia",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia"),
        ),
        migrations.AlterField(
            model_name="area",
            name="updated_in_mneia",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia"),
        ),
        migrations.AlterField(
            model_name="areatype",
            name="created_in_mneia",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia"),
        ),
        migrations.AlterField(
            model_name="areatype",
            name="updated_in_mneia",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia"),
        ),
        migrations.AlterField(
            model_name="gender",
            name="created_in_mneia",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia"),
        ),
        migrations.AlterField(
            model_name="gender",
            name="updated_in_mneia",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia"),
        ),
        migrations.AlterField(
            model_name="link",
            name="created_in_mneia",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia"),
        ),
        migrations.AlterField(
            model_name="link",
            name="updated_in_mneia",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia"),
        ),
        migrations.AlterField(
            model_name="linkattribute",
            name="attribute_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="mneia_backend.linkattributetype",
                verbose_name="Link Attribute",
            ),
        ),
        migrations.AlterField(
            model_name="linkattribute",
            name="created_in_mneia",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia"),
        ),
        migrations.AlterField(
            model_name="linkattribute",
            name="updated_in_mneia",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia"),
        ),
        migrations.AlterField(
            model_name="linkattributetextvalue",
            name="created_in_mneia",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia"),
        ),
        migrations.AlterField(
            model_name="linkattributetextvalue",
            name="updated_in_mneia",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia"),
        ),
        migrations.AlterField(
            model_name="linkattributetype",
            name="created_in_mneia",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia"),
        ),
        migrations.AlterField(
            model_name="linkattributetype",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_link_attribute_types",
                to="mneia_backend.linkattributetype",
            ),
        ),
        migrations.AlterField(
            model_name="linkattributetype",
            name="root",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leaf_child_attribute_types",
                to="mneia_backend.linkattributetype",
            ),
        ),
        migrations.AlterField(
            model_name="linkattributetype",
            name="updated_in_mneia",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia"),
        ),
        migrations.AlterField(
            model_name="linkmagazineissuephotograph",
            name="created_in_mneia",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia"),
        ),
        migrations.AlterField(
            model_name="linkmagazineissuephotograph",
            name="updated_in_mneia",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia"),
        ),
        migrations.AlterField(
            model_name="linkpersonphotograph",
            name="created_in_mneia",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia"),
        ),
        migrations.AlterField(
            model_name="linkpersonphotograph",
            name="updated_in_mneia",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia"),
        ),
        migrations.AlterField(
            model_name="linktextattributetype",
            name="attribute_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="mneia_backend.linkattributetype",
                verbose_name="Attribute Type",
            ),
        ),
        migrations.AlterField(
            model_name="linktextattributetype",
            name="created_in_mneia",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia"),
        ),
        migrations.AlterField(
            model_name="linktextattributetype",
            name="updated_in_mneia",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia"),
        ),
        migrations.AlterField(
            model_name="linktype",
            name="created_in_mneia",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia"),
        ),
        migrations.AlterField(
            model_name="linktype",
            name="entity_type0",
            field=models.CharField(
                choices=[("person", "person"), ("magazine_issue", "magazine_issue")],
                max_length=50,
                verbose_name="Entity Type 0",
            ),
        ),
        migrations.AlterField(
            model_name="linktype",
            name="updated_in_mneia",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia"),
        ),
        migrations.AlterField(
            model_name="magazine",
            name="created_in_mneia",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia"),
        ),
        migrations.AlterField(
            model_name="magazine",
            name="updated_in_mneia",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia"),
        ),
        migrations.AlterField(
            model_name="magazineissue",
            name="created_in_mneia",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia"),
        ),
        migrations.AlterField(
            model_name="magazineissue",
            name="updated_in_mneia",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia"),
        ),
        migrations.AlterField(
            model_name="person",
            name="created_in_mneia",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia"),
        ),
        migrations.AlterField(
            model_name="person",
            name="updated_in_mneia",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia"),
        ),
        migrations.AlterField(
            model_name="photograph",
            name="created_in_mneia",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia"),
        ),
        migrations.AlterField(
            model_name="photograph",
            name="updated_in_mneia",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia"),
        ),
    ]
