# Generated by Django 5.1.5 on 2025-01-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0016_alter_linkmagazineissuephotograph_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="magazineissue",
            options={"ordering": ["order"], "verbose_name_plural": "Magazine Issues"},
        ),
        migrations.AlterField(
            model_name="magazineissue",
            name="magazine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="issues", to="mneia_backend.magazine"
            ),
        ),
    ]
