# Generated by Django 5.1.5 on 2025-01-27 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0018_alter_linkattribute_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkpersonphotograph",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="links_to_photographs",
                to="mneia_backend.person",
            ),
        ),
        migrations.AlterField(
            model_name="linkpersonphotograph",
            name="photograph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="links_to_people",
                to="mneia_backend.photograph",
            ),
        ),
    ]
