# Generated by Django 5.1.5 on 2025-01-28 19:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0019_alter_linkpersonphotograph_person_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia")),
                ("updated_in_mneia", models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia")),
                ("mbid", models.IntegerField(blank=True, null=True, verbose_name="MBID")),
                ("name", models.CharField(max_length=255)),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("edits_pending", models.PositiveIntegerField(default=0, verbose_name="Edits Pending")),
                ("last_updated", models.DateTimeField(auto_now=True, verbose_name="Last Updated")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="linktype",
            name="entity_type1",
            field=models.CharField(
                choices=[("photograph", "photograph"), ("work", "work")], max_length=50, verbose_name="Entity Type 1"
            ),
        ),
        migrations.CreateModel(
            name="LinkPersonWork",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia")),
                ("updated_in_mneia", models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia")),
                (
                    "mbid",
                    models.IntegerField(
                        blank=True, help_text="The MusicBrainz integer ID", null=True, verbose_name="MBID"
                    ),
                ),
                ("edits_pending", models.PositiveIntegerField(default=0, verbose_name="Edits Pending")),
                ("last_updated", models.DateTimeField(auto_now=True, verbose_name="Last Updated")),
                ("link_order", models.PositiveIntegerField(default=0, null=True, verbose_name="Link Order")),
                ("entity0_credit", models.TextField(blank=True, default="")),
                ("entity1_credit", models.TextField(blank=True, default="")),
                ("link", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.link")),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links_to_works",
                        to="mneia_backend.person",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links_to_people",
                        to="mneia_backend.work",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Links Person - Work",
            },
        ),
        migrations.CreateModel(
            name="WorkType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia")),
                ("updated_in_mneia", models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia")),
                ("mbid", models.IntegerField(help_text="The MusicBrainz integer ID", verbose_name="MBID")),
                ("name", models.CharField(max_length=255)),
                ("child_order", models.IntegerField(verbose_name="Child Order")),
                ("description", models.TextField(null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.worktype"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Work Types",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="work",
            name="type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.worktype"),
        ),
    ]
