# Generated by Django 5.1.5 on 2025-01-29 16:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0020_work_alter_linktype_entity_type1_linkpersonwork_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkMagazineIssueWork",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia")),
                ("updated_in_mneia", models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia")),
                (
                    "mbid",
                    models.IntegerField(
                        blank=True, help_text="The MusicBrainz integer ID", null=True, verbose_name="MBID"
                    ),
                ),
                ("edits_pending", models.PositiveIntegerField(default=0, verbose_name="Edits Pending")),
                ("last_updated", models.DateTimeField(auto_now=True, verbose_name="Last Updated")),
                ("link_order", models.PositiveIntegerField(default=0, null=True, verbose_name="Link Order")),
                ("entity0_credit", models.TextField(blank=True, default="")),
                ("entity1_credit", models.TextField(blank=True, default="")),
                ("link", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.link")),
                (
                    "magazine_issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links_to_works",
                        to="mneia_backend.magazineissue",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links_to_magazine_issues",
                        to="mneia_backend.work",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Links Magazine Issue - Work",
            },
        ),
    ]
