# Generated by Django 5.1.5 on 2025-01-30 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0021_linkmagazineissuework"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="link",
            options={"verbose_name": "Link", "verbose_name_plural": "Links"},
        ),
        migrations.AlterModelOptions(
            name="linkattribute",
            options={"verbose_name": "Link Attribute", "verbose_name_plural": "Link Attributes"},
        ),
        migrations.AlterModelOptions(
            name="linkmagazineissuephotograph",
            options={
                "verbose_name": "Link Magazine Issue - Photograph",
                "verbose_name_plural": "Links Magazine Issue - Photograph",
            },
        ),
        migrations.AlterModelOptions(
            name="linkpersonphotograph",
            options={"verbose_name": "Link Person - Photograph", "verbose_name_plural": "Links Person - Photograph"},
        ),
        migrations.AlterModelOptions(
            name="linkpersonwork",
            options={"verbose_name": "Link Person - Work", "verbose_name_plural": "Links Person - Work"},
        ),
        migrations.AlterModelOptions(
            name="linktype",
            options={"verbose_name": "Link Type", "verbose_name_plural": "Link Types"},
        ),
        migrations.AlterField(
            model_name="linkmagazineissuephotograph",
            name="link",
            field=models.ForeignKey(
                limit_choices_to={"link_type__entity_type0": "magazine_issue", "link_type__entity_type1": "photograph"},
                on_delete=django.db.models.deletion.PROTECT,
                to="mneia_backend.link",
            ),
        ),
        migrations.AlterField(
            model_name="linkmagazineissuework",
            name="link",
            field=models.ForeignKey(
                limit_choices_to={"link_type__entity_type0": "magazine_issue", "link_type__entity_type1": "work"},
                on_delete=django.db.models.deletion.PROTECT,
                to="mneia_backend.link",
            ),
        ),
        migrations.AlterField(
            model_name="linkpersonphotograph",
            name="link",
            field=models.ForeignKey(
                limit_choices_to={"link_type__entity_type0": "person", "link_type__entity_type1": "photograph"},
                on_delete=django.db.models.deletion.PROTECT,
                to="mneia_backend.link",
            ),
        ),
        migrations.AlterField(
            model_name="linkpersonwork",
            name="link",
            field=models.ForeignKey(
                limit_choices_to={"link_type__entity_type0": "person", "link_type__entity_type1": "work"},
                on_delete=django.db.models.deletion.PROTECT,
                to="mneia_backend.link",
            ),
        ),
    ]
