# Generated by Django 5.1.5 on 2025-01-30 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0022_alter_link_options_alter_linkattribute_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areatype",
            name="child_order",
            field=models.IntegerField(default=0, verbose_name="Child Order"),
        ),
        migrations.AlterField(
            model_name="areatype",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="areatype",
            name="mbid",
            field=models.IntegerField(
                blank=True, help_text="The MusicBrainz integer ID", null=True, verbose_name="MBID"
            ),
        ),
        migrations.AlterField(
            model_name="areatype",
            name="parent",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.areatype"
            ),
        ),
        migrations.AlterField(
            model_name="gender",
            name="child_order",
            field=models.IntegerField(default=0, verbose_name="Child Order"),
        ),
        migrations.AlterField(
            model_name="gender",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gender",
            name="mbid",
            field=models.IntegerField(
                blank=True, help_text="The MusicBrainz integer ID", null=True, verbose_name="MBID"
            ),
        ),
        migrations.AlterField(
            model_name="gender",
            name="parent",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.gender"
            ),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="child_order",
            field=models.IntegerField(default=0, verbose_name="Child Order"),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="mbid",
            field=models.IntegerField(
                blank=True, help_text="The MusicBrainz integer ID", null=True, verbose_name="MBID"
            ),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="parent",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.worktype"
            ),
        ),
    ]
