# Generated by Django 5.1.5 on 2025-01-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0023_alter_areatype_child_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worktype",
            name="greek_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="magazineissue",
            constraint=models.UniqueConstraint(
                fields=("magazine", "issue_number"), name="do_not_repeat_issue_numbers_for_the_same_magazine"
            ),
        ),
    ]
