# Generated by Django 5.1.5 on 2025-02-08 09:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0025_alter_magazineissue_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linktype",
            name="parent",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.linktype"
            ),
        ),
        migrations.CreateModel(
            name="BookFormat",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia")),
                ("updated_in_mneia", models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia")),
                (
                    "mbid",
                    models.IntegerField(
                        blank=True, help_text="The MusicBrainz integer ID", null=True, verbose_name="MBID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("child_order", models.IntegerField(default=0, verbose_name="Child Order")),
                ("description", models.TextField(blank=True, null=True)),
                ("greek_name", models.CharField(blank=True, max_length=255, null=True, verbose_name="Greek Name")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mneia_backend.bookformat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Format",
                "verbose_name_plural": "Book Formats",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
    ]
