# Generated by Django 5.1.5 on 2025-02-08 09:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0026_alter_linktype_parent_bookformat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia")),
                ("updated_in_mneia", models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia")),
                ("name", models.CharField(max_length=255)),
                ("edition", models.CharField(max_length=255)),
                ("isbn", models.CharField(blank=True, max_length=13, null=True)),
                (
                    "pages_number",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="The number of pages in this book", null=True, verbose_name="Pages Number"
                    ),
                ),
                (
                    "publication_date_year",
                    models.SmallIntegerField(blank=True, null=True, verbose_name="Publication Date Year"),
                ),
                (
                    "publication_date_month",
                    models.SmallIntegerField(blank=True, null=True, verbose_name="Publication Date Month"),
                ),
                (
                    "publication_date_day",
                    models.SmallIntegerField(blank=True, null=True, verbose_name="Publication Date Day"),
                ),
                (
                    "format",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="books", to="mneia_backend.bookformat"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
