# Generated by Django 5.1.5 on 2025-02-09 07:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0028_alter_book_isbn_alter_linktype_entity_type0_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia")),
                ("updated_in_mneia", models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia")),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
