# Generated by Django 5.1.5 on 2025-02-09 07:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0029_publisher"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publisher",
            options={"verbose_name": "Publisher", "verbose_name_plural": "Publishers"},
        ),
        migrations.AlterField(
            model_name="linktype",
            name="entity_type1",
            field=models.CharField(
                choices=[
                    ("person", "person"),
                    ("photograph", "photograph"),
                    ("publisher", "publisher"),
                    ("work", "work"),
                ],
                max_length=50,
                verbose_name="Entity Type 1",
            ),
        ),
        migrations.CreateModel(
            name="LinkBookPublisher",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_in_mneia", models.DateTimeField(auto_now_add=True, verbose_name="Created in Mneia")),
                ("updated_in_mneia", models.DateTimeField(auto_now=True, verbose_name="Updated in Mneia")),
                (
                    "mbid",
                    models.IntegerField(
                        blank=True, help_text="The MusicBrainz integer ID", null=True, verbose_name="MBID"
                    ),
                ),
                ("edits_pending", models.PositiveIntegerField(default=0, verbose_name="Edits Pending")),
                ("last_updated", models.DateTimeField(auto_now=True, verbose_name="Last Updated")),
                ("link_order", models.PositiveIntegerField(default=0, null=True, verbose_name="Link Order")),
                ("entity0_credit", models.TextField(blank=True, default="")),
                ("entity1_credit", models.TextField(blank=True, default="")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links_to_publishers",
                        to="mneia_backend.book",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        limit_choices_to={"link_type__entity_type0": "book", "link_type__entity_type1": "publisher"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mneia_backend.link",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links_to_books",
                        to="mneia_backend.publisher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link Book - Publisher",
                "verbose_name_plural": "Links Book - Publisher",
            },
        ),
    ]
