# Generated by Django 5.1.5 on 2025-02-09 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0030_alter_publisher_options_alter_linktype_entity_type1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="area",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="mneia_backend.area"
            ),
        ),
    ]
