# Generated by Django 5.1.5 on 2025-02-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mneia_backend", "0031_book_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="greek_name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Greek Name"),
        ),
    ]
